import { EventEmitter, OnInit, ElementRef, OnChanges, SimpleChanges, Renderer2, TemplateRef, OnDestroy } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { FilterPipe } from './filter.pipe';
import * as i0 from "@angular/core";
export declare class NgxContactListComponent implements OnInit, OnChanges, OnDestroy {
    private filter;
    private renderer;
    private formBuilder;
    templateRef: TemplateRef<any>;
    inputBodyEl: ElementRef<HTMLElement>;
    inputSearchEl: ElementRef<HTMLElement>;
    searchListEl: ElementRef<HTMLElement>;
    letterList: ElementRef<HTMLElement>;
    indicatorEl: ElementRef<HTMLElement>;
    contentEl: ElementRef<HTMLElement>;
    height: string;
    propAlphaOrder: string;
    propsSearch: any;
    data: any[];
    placeholder: string;
    listClass: string;
    withTemplate: boolean;
    noSmoothScroll: boolean;
    onCancel: EventEmitter<any>;
    onClick: EventEmitter<any>;
    form: FormGroup;
    closed: boolean;
    objFilter: any;
    inputFocused: boolean;
    heightContent: number;
    alphabet: string[];
    currentAlpha: string;
    currentLetterElement: any;
    hiddenTitle: boolean;
    lettersListHeight: number;
    indicatorClicked: boolean;
    private goingToLetter;
    constructor(filter: FilterPipe, renderer: Renderer2, formBuilder: FormBuilder);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    defineCurrentLetterElement(): void;
    goLetter(letter: string): void;
    onMouseMoveContent(event: any): void;
    onMouseDownIndicator(event: any): void;
    onMouseUpIndicator(): void;
    onMouseUpContent(): void;
    onScrollList(e: any): void;
    onMouseWheelContent(event: any): void;
    onKeyDownContent(event: KeyboardEvent): void;
    click(data?: any): void;
    close(): void;
    focusInput(): void;
    startsWithLetter(_letter: string): boolean;
    setFilter(): void;
    clearFilter(): void;
    private orderBy;
    ngOnDestroy(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<NgxContactListComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NgxContactListComponent, "ngx-contact-list", never, { "height": "height"; "propAlphaOrder": "propAlphaOrder"; "propsSearch": "propsSearch"; "data": "data"; "placeholder": "placeholder"; "listClass": "listClass"; "withTemplate": "withTemplate"; "noSmoothScroll": "noSmoothScroll"; }, { "onCancel": "onCancel"; "onClick": "onClick"; }, ["templateRef"], never, false>;
}
